name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天 0 点 UTC 自动运行

permissions:
  contents: write  # 必须有，WakaReadme 要写回 README

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Update WakaTime stats in README
        if: ${{ github.event_name != 'pull_request' }} # 避免 PR 时 secrets 不可用
        uses: athul/waka-readme@v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_TOTAL: true
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMIT_MESSAGE: "docs: update WakaTime stats"
          SECTION_NAME: "waka"
